### ISSUE TITLE
XRD Plugin: Phi and Omega Rotation Scanning Data and Reciprocal Space Mapping  (RSM) Data are not parsed

### ISSUE THREAD

**Issue by haltugyildirim** [FAIRmat-NFDI/nomad-measurements#62]
When I try to use XRD plugin (from commit: [8326872c40ec41cdbd4e5ca82ae40aa4abd47b86](https://github.com/FAIRmat-NFDI/nomad-measurements/commit/8326872c40ec41cdbd4e5ca82ae40aa4abd47b86)) in the path `https://github.com/FAIRmat-NFDI/nomad-measurements/tree/main/src/nomad_measurements/xrd`  with a scan involving a single angle rotation,  I get this error from log:

```
"root":{
"normalizer":string"MetainfoNormalizer"
"section":string"ELNXRayDiffraction"
"event":string"could not normalize section"
"proc":string"Entry"
"process":string"process_entry_local"
"process_worker_id":string"AVDEYx0XSMO5hpT00-iGQA"
"parser":string"parsers/archive"
"step":string"MetainfoNormalizer"
"logger":string"nomad.processing"
"exception":string"Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/nomad/normalizing/metainfo.py", line 35, in normalize_section normalize(self.entry_archive, logger) File "/app/plugins/nomad_measurements/xrd/schema.py", line 671, in normalize line_linear = px.line( File "/usr/local/lib/python3.9/site-packages/plotly/express/_chart_types.py", line 264, in line return make_figure(args=locals(), constructor=go.Scatter) File "/usr/local/lib/python3.9/site-packages/plotly/express/_core.py", line 1990, in make_figure args = build_dataframe(args, constructor) File "/usr/local/lib/python3.9/site-packages/plotly/express/_core.py", line 1405, in build_dataframe df_output, wide_id_vars = process_args_into_dataframe( File "/usr/local/lib/python3.9/site-packages/plotly/express/_core.py", line 1245, in process_args_into_dataframe raise ValueError( ValueError: All arguments should have the same length. The length of argument `y` is 1799, whereas the length of previously-processed arguments ['x'] is 1"
"timestamp":string"2023-12-12 16:23.40"
"level":string"ERROR"
}

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nomad/normalizing/metainfo.py", line 35, in normalize_section
    normalize(self.entry_archive, logger)
  File "/app/plugins/nomad_measurements/xrd/schema.py", line 671, in normalize
    line_linear = px.line(
  File "/usr/local/lib/python3.9/site-packages/plotly/express/_chart_types.py", line 264, in line
    return make_figure(args=locals(), constructor=go.Scatter)
  File "/usr/local/lib/python3.9/site-packages/plotly/express/_core.py", line 1990, in make_figure
    args = build_dataframe(args, constructor)
  File "/usr/local/lib/python3.9/site-packages/plotly/express/_core.py", line 1405, in build_dataframe
    df_output, wide_id_vars = process_args_into_dataframe(
  File "/usr/local/lib/python3.9/site-packages/plotly/express/_core.py", line 1245, in process_args_into_dataframe
    raise ValueError(
ValueError: All arguments should have the same length. The length of argument `y` is 1799, whereas the length of  previously-processed arguments ['x'] is 1
```
* Parser seems to be load the right `intensity` array, but not the right angle array as the length of `x` and `y` arrays differ.

* First array of RSM scan is parsed and plotted, contrary to Omega and Phi scans which are not parsed at all. It gives the warning as below:

```
"root":{
"normalizer":string"MetainfoNormalizer"
"event":string"Multi scan xrdml files are currently not supported. Only reading first scan."
"proc":string"Entry"
"process":string"process_entry_local"
"process_worker_id":string"r0DEmXsSRj6kevubiBdhKA"
"parser":string"parsers/archive"
"step":string"MetainfoNormalizer"
"logger":string"nomad.processing"
"timestamp":string"2023-12-15 12:43.15"
"level":string"WARNING"
```

* All data files uploaded have file format of `*.xrdml`

**Comment by ka-sarthak** [comment]
Hi @haltugyildirim, I am sorry for the delay in getting back to you. Is this still an issue? If so, can you share the raw xrd file with me?
